[package]
name = "tuto"
version = "0.1"
lean_version = "leanprover-community/lean:3.49.1"
path = "src/solutions"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "568eb9b432c885f2a2cb8fe3bbfa77467e774da7"}
