[package]
name = "tuto"
version = "0.1"
lean_version = "leanprover-community/lean:3.23.0"
path = "src/solutions"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "4aa087aa4b424a64a4673cee7fbf670aac04470a"}
