[package]
name = "tuto"
version = "0.1"
lean_version = "leanprover-community/lean:3.35.0"
path = "src/solutions"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "ae98aad6ef2e141d89ca1540b270a4dd5b4ecea6"}
