[package]
name = "tuto"
version = "0.1"
lean_version = "leanprover-community/lean:3.32.1"
path = "src/solutions"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "2bae06af885ff136576e84f1f03df9e296333e7e"}
