[package]
name = "tuto"
version = "0.1"
lean_version = "leanprover-community/lean:3.27.0"
path = "src/solutions"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "0a16148c452052e085533e2b995421a571208dd6"}
