[package]
name = "tuto"
version = "0.1"
lean_version = "leanprover-community/lean:3.35.1"
path = "src/solutions"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "0c8f53e529ae28343a04cf972f85a1bfbea05485"}
