[package]
name = "tuto"
version = "0.1"
lean_version = "leanprover-community/lean:3.44.1"
path = "src/solutions"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "ad080011af3850e6e6daa0bf4e593f43273894e4"}
