[package]
name = "tuto"
version = "0.1"
lean_version = "leanprover-community/lean:3.42.1"
path = "src/solutions"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "e6322c6acc2a71447ce123bed4fae533f0ced711"}
