[package]
name = "tuto"
version = "0.1"
lean_version = "leanprover-community/lean:3.10.0"
path = "src/solutions"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "96efc220f6225bc7a5ed8349900391a33a38cc56"}
