[package]
name = "tuto"
version = "0.1"
lean_version = "leanprover-community/lean:3.9.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "b14a26ee31a482c5f3d26069876481988b2c746f"}
