on:
  schedule:
   - cron: '0 0 * * 2'

jobs:
  publish_archive_job:
    runs-on: ubuntu-latest
    name: Bump Lean and mathlib versions
    steps:
      - uses: actions/checkout@v2
      - name: install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: install Python dependencies
        run: python -m pip install --upgrade pip mathlibtools
      - name: install Lean
        run: |
          curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- -y
          echo "::add-path::$HOME/.elan/bin"
      - name: upgrade project
        run: leanproject up
      - name: build project 
        run: lean src
      - name: push changes
        run: |
          git config --global user.email "leanprover.community@gmail.com"
          git config --global user.name "leanprover-community-bot"
          git commit -am "auto update Lean/mathlib versions" || true
          git push || true
